"""Init command implementation for wetwire-gitlab.

This module provides package scaffolding functionality for creating
new wetwire-gitlab pipeline projects.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def create_package(
    output_dir: Path,
    name: str,
    description: str | None = None,
    no_scaffold: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    """Create a new wetwire-gitlab package.

    Args:
        output_dir: Directory where the package should be created.
        name: Name of the package (snake_case).
        description: Optional description for the package.
        no_scaffold: If True, skip README, CLAUDE.md, .gitignore.
        force: If True, overwrite existing package.

    Returns:
        Dict with 'success' and 'message' or 'error' keys.
    """
    # Validate module name
    if not name.replace("_", "").isalnum():
        return {
            "success": False,
            "error": f"Invalid module name '{name}'. Use snake_case with letters, numbers, and underscores only.",
        }

    # Ensure output directory exists
    output_dir = Path(output_dir)
    if not output_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)

    package_dir = output_dir / name
    desc = description or f"{name} GitLab CI/CD pipeline"

    # Check if package exists
    if package_dir.exists() and not force:
        return {
            "success": False,
            "error": f"Package already exists: {package_dir}. Use --force to overwrite.",
        }

    # Create or recreate package directory
    if package_dir.exists() and force:
        import shutil
        shutil.rmtree(package_dir)

    package_dir.mkdir(parents=True, exist_ok=True)

    created_files: list[str] = []

    # Create __init__.py
    init_content = f'''"""{desc}

Generated by wetwire-gitlab init.
"""

from .jobs import *  # noqa: F403, F401
from .pipeline import *  # noqa: F403, F401
'''
    (package_dir / "__init__.py").write_text(init_content)
    created_files.append(f"{name}/__init__.py")

    # Create pipeline.py
    pipeline_content = '''"""Pipeline configuration."""

from wetwire_gitlab.pipeline import Pipeline

pipeline = Pipeline(
    stages=["build", "test", "deploy"],
)
'''
    (package_dir / "pipeline.py").write_text(pipeline_content)
    created_files.append(f"{name}/pipeline.py")

    # Create jobs.py
    jobs_content = '''"""Job definitions."""

from wetwire_gitlab.intrinsics import Rules
from wetwire_gitlab.pipeline import Job

build = Job(
    name="build",
    stage="build",
    script=["echo 'Building...'"],
)

test = Job(
    name="test",
    stage="test",
    script=["echo 'Testing...'"],
    needs=["build"],
)

deploy = Job(
    name="deploy",
    stage="deploy",
    script=["echo 'Deploying...'"],
    rules=[Rules.ON_DEFAULT_BRANCH],
    needs=["test"],
)
'''
    (package_dir / "jobs.py").write_text(jobs_content)
    created_files.append(f"{name}/jobs.py")

    # Create scaffold files (unless --no-scaffold)
    if not no_scaffold:
        # README.md
        readme_content = f'''# {name}

GitLab CI/CD pipeline configuration using wetwire-gitlab.

## Usage

Build the .gitlab-ci.yml:

```bash
wetwire-gitlab build {name}/
```

Validate the configuration:

```bash
wetwire-gitlab validate .gitlab-ci.yml
```

Lint the Python code:

```bash
wetwire-gitlab lint {name}/
```

## Structure

```
{name}/
├── __init__.py      # Package initialization
├── pipeline.py      # Pipeline configuration (stages)
└── jobs.py          # Job definitions
```

## Customization

Edit `jobs.py` to add your pipeline jobs. Use typed dataclasses:

```python
from wetwire_gitlab.pipeline import Job, Artifacts
from wetwire_gitlab.intrinsics import Rules

my_job = Job(
    name="my-job",
    stage="build",
    script=["make build"],
    artifacts=Artifacts(paths=["dist/"]),
    rules=[Rules.ON_DEFAULT_BRANCH],
)
```

## Resources

- [wetwire-gitlab Documentation](https://github.com/lex00/wetwire-gitlab-python)
- [GitLab CI/CD Documentation](https://docs.gitlab.com/ee/ci/)
'''
        (output_dir / "README.md").write_text(readme_content)
        created_files.append("README.md")

        # CLAUDE.md
        claude_content = f'''# {name}

GitLab CI/CD pipeline configuration using wetwire-gitlab typed Python declarations.

## Syntax Principles

All configurations use typed Python dataclasses. No raw dictionaries, no string templates.

### Jobs

```python
from wetwire_gitlab.pipeline import Job, Artifacts
from wetwire_gitlab.intrinsics import Rules

build = Job(
    name="build",
    stage="build",
    script=["make build"],
    artifacts=Artifacts(paths=["build/"]),
)
```

### Pipelines

```python
from wetwire_gitlab.pipeline import Pipeline

pipeline = Pipeline(stages=["build", "test", "deploy"])
```

### CI Variables

Use typed variable namespaces:

```python
from wetwire_gitlab.intrinsics import CI, GitLab, MR

CI.COMMIT_SHA          # $CI_COMMIT_SHA
CI.DEFAULT_BRANCH      # $CI_DEFAULT_BRANCH
GitLab.USER_LOGIN      # $GITLAB_USER_LOGIN
MR.SOURCE_BRANCH       # $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
```

### Pre-defined Rules

```python
from wetwire_gitlab.intrinsics import Rules

deploy = Job(
    name="deploy",
    rules=[Rules.ON_DEFAULT_BRANCH],
)
```

## Build

```bash
wetwire-gitlab build {name}/
# Outputs .gitlab-ci.yml
```
'''
        (output_dir / "CLAUDE.md").write_text(claude_content)
        created_files.append("CLAUDE.md")

        # .gitignore
        gitignore_content = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.env
.venv
env/
venv/
ENV/

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/
.nox/

# wetwire-gitlab
.gitlab-ci.yml
'''
        (output_dir / ".gitignore").write_text(gitignore_content)
        created_files.append(".gitignore")

    return {
        "success": True,
        "message": f"Created package: {package_dir}",
        "path": str(package_dir),
        "files": created_files,
    }
