"""Linter module for wetwire-gitlab."""

from .linter import fix_code, fix_file, lint_code, lint_directory, lint_file
from .rules import (
    ALL_RULES,
    RULE_REGISTRY,
    WGL001TypedComponentWrappers,
    WGL002UseRuleDataclass,
    WGL003UsePredefinedVariables,
    WGL004UseCacheDataclass,
    WGL005UseArtifactsDataclass,
    WGL006UseTypedStageConstants,
    WGL007DuplicateJobNames,
    WGL008FileTooLarge,
    WGL009UsePredefinedRules,
    WGL010UseTypedWhenConstants,
    WGL011MissingStage,
    WGL012UseCachePolicyConstants,
    WGL013UseArtifactsWhenConstants,
    WGL014MissingScript,
    WGL015MissingName,
    WGL016UseImageDataclass,
    WGL017EmptyRulesList,
    WGL018NeedsWithoutStage,
    WGL019ManualWithoutAllowFailure,
)

__all__ = [
    "ALL_RULES",
    "RULE_REGISTRY",
    "WGL001TypedComponentWrappers",
    "WGL002UseRuleDataclass",
    "WGL003UsePredefinedVariables",
    "WGL004UseCacheDataclass",
    "WGL005UseArtifactsDataclass",
    "WGL006UseTypedStageConstants",
    "WGL007DuplicateJobNames",
    "WGL008FileTooLarge",
    "WGL009UsePredefinedRules",
    "WGL010UseTypedWhenConstants",
    "WGL011MissingStage",
    "WGL012UseCachePolicyConstants",
    "WGL013UseArtifactsWhenConstants",
    "WGL014MissingScript",
    "WGL015MissingName",
    "WGL016UseImageDataclass",
    "WGL017EmptyRulesList",
    "WGL018NeedsWithoutStage",
    "WGL019ManualWithoutAllowFailure",
    "fix_code",
    "fix_file",
    "lint_code",
    "lint_directory",
    "lint_file",
]
